version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # Đổi mật khẩu root
      MYSQL_DATABASE: DIB      # Đổi tên database mặc định
      MYSQL_USER: user                    # Đổi username
      MYSQL_PASSWORD: passwordofuser   # Đổi mật khẩu của user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: